config/routes.rb
Rails.application.routes.draw do
  resources :home, only: %i[index]
  resources :external_transactions, only: %i[index]
  resources :group_transactions, only: %i[create new] do
    match '/new', to: 'group_transactions#create', via: :post, on: :collection
  end
  resources :user_transactions do
    put :update_payments, on: :member
    put :archieve_payments, on: :member
    get :archieved_transactions, on: :collection
  end
  resources :groups
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  before_action :set_user_transaction, only: %i[show edit update destroy]

  # GET /user_transactions or /user_transactions.json
  def index
    @user_transactions = current_user.user_transactions.archieved.order(created_at: :desc)
  end

  def archieved_transactions
    @user_transactions = current_user.user_transactions.not_archieved.order(updated_at: :desc)
  end

  # GET /user_transactions/1 or /user_transactions/1.json
  def show
    @group_transactions = Group.all
    @group_transaction = GroupTransaction.new
  end

  # GET /user_transactions/new
  def new
    @user_transaction = UserTransaction.new
  end

  # GET /user_transactions/1/edit
  def edit
    # edit
  end

  # POST /user_transactions or /user_transactions.json
  def create
    @user_transaction = UserTransaction.new(user_transaction_params)

    respond_to do |format|
      if @user_transaction.save
        format.html { redirect_to @user_transaction, notice: 'User transaction was successfully created.' }
        format.json { render :show, status: :created, location: @user_transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_transactions/1 or /user_transactions/1.json
  def update
    respond_to do |format|
      if @user_transaction.update(user_transaction_params)
        format.html { redirect_to @user_transaction, notice: 'User transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_transactions/1 or /user_transactions/1.json
  def destroy
    @user_transaction.destroy
    respond_to do |format|
      format.html { redirect_to user_transactions_url, notice: 'User transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_payments
    @updated_payment = UserTransaction.find(params[:id])
    @updated_payment.update_payment

    redirect_to user_transactions_url
  end

  def archieve_payments
    @updated_payments = UserTransaction.find(params[:id])
    @updated_payments.archieve_payments

    redirect_to archieved_transactions_user_transactions_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_transaction
    @user_transaction = UserTransaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_transaction_params
    params.require(:user_transaction).permit(:name, :amount, :user_id, :is_paid)
  end
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
end

app/views/user_transactions/_form.html.erb
<%= form_with(model: user_transaction, local: true) do |form| %>
  <% if user_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_transaction.errors.count, "error") %> prohibited this user_transaction from being saved:</h2>

      <ul>
        <% user_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:'label' %>
    <%= form.text_field :name, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :amount, class:"label" %>
    <%= form.text_field :amount, class:"input" %>
  </div>

  <div class="field">
    <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-success is-fullwidth" %>
  </div>
<% end %>

app/views/user_transactions/archieved_transactions.html.erb
<div class="columns is-centered">
  <div class="column is-7-desktop is-12-mobile is-12-mobile">
    <div class="card card-content">
      <div class="content">
        <p id="notice"><%= notice %></p>

        <h1 class="has-text-centered">Archieved Transactions</h1>

        <div class="columns is-centered is-flex-mobile">
          <div class="column is-4">
            <u><strong>Total Amount</strong></u>
          </div>
          <div class="column is-4 has-text-right">
            $<%= archieved_total_transactions %>
          </div>
        </div>

        <% @user_transactions.each do |user_transaction| %>
          <div class="box">
            <div class="columns">
              <div class="column is-9">
                <%= link_to user_transaction do %>
                  <div class="columns has-text-dark is-flex-mobile">
                    <div class="column is-4">
                      <span>
                        <%= icon(first_transaction_icon(user_transaction.id))%>
                        <span class="is-size-4">
                          <%= user_transaction.name.capitalize %>
                        </span>
                      </span>
                    </div>
                    <div class="column is-2 has-text-centered">
                      <span class="is-size-5">$<%= user_transaction.amount %></span>
                    </div>

                    <div class="column is-4 has-text-right">
                      <span class="is-size-6"><i><%= user_transaction.updated_at.strftime("%d %b %Y") %></i></span>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="column is-3">
                <%= form_for user_transaction, :url => [:archieve_payments, user_transaction], html: { method: :put } do |f| %>
                  <%= f.submit 'Reverse Payment', class:'button is-primary px-0' %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', user_transactions_path, class:"button is-dark mt-3" %>
  </div>
</div>

app/views/user_transactions/edit.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-mobile">
    <div class="card">
      <div class="card-content">
        <div class="content">
          <h1 class="has-text-centered">Editing Transaction</h1>

          <%= render 'form', user_transaction: @user_transaction %>
        </div>
      </div>
      <footer class="card-footer">
        <div class="column is-6 has-text-centered">
          <%= link_to 'Show', @user_transaction, class:"card-footer-items button is-success is-fullwidth" %>
        </div>
        <div class="column is-6 has-text-centered">
          <%= link_to 'Back', user_transactions_path, class:"card-footer-items button is-dark is-fullwidth" %>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/user_transactions/index.html.erb
<div class="columns is-centered">
  <div class="column is-7-desktop is-12-mobile is-12-mobile">
    <div class="card card-content">
      <div class="content">
        <p id="notice"><%= notice %></p>

        <h1 class="has-text-centered">All Transactions</h1>

        <div class="columns is-centered is-flex-mobile">
          <div class="column is-4">
            <u><strong>Total Amount</strong></u>
          </div>
          <div class="column is-4 has-text-right">
            $<%= user_total_transactions %>
          </div>
        </div>

        <% @user_transactions.each do |user_transaction| %>
          <div class="box">
            <div class="columns">
              <div class="column is-9">
                <%= link_to user_transaction do %>
                  <div class="columns has-text-dark is-flex-mobile">
                    <div class="column is-4">
                      <span>
                        <%= icon(first_transaction_icon(user_transaction.id))%>
                        <span class="is-size-4">
                          <%= user_transaction.name.capitalize %>
                        </span>
                      </span>
                    </div>
                    <div class="column is-2 has-text-centered">
                      <span class="is-size-5">$<%= user_transaction.amount %></span>
                    </div>

                    <div class="column is-4 has-text-right">
                      <span class="is-size-6"><i><%= user_transaction.created_at.strftime("%d %b %Y") %></i></span>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="column is-3">
                <%= form_for user_transaction, :url => [:update_payments, user_transaction], html: { method: :put } do |f| %>
                  <%= f.submit 'Archieve Payment', class:'button is-danger' %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to 'Add New Transaction', new_user_transaction_path, class:"button is-success mt-3 is-fullwidth" %>
    <%= link_to 'Click to see Archieved Payments', archieved_transactions_user_transactions_path, class:"button is-primary mt-3 is-fullwidth" %>
  </div>
</div>

app/views/user_transactions/new.html.erb
<div class="columns is-centered">
  <div class="column is-5-desktop is-12-mobile is-12-mobile">
    <div class="card">
      <div class="card-content">
        <div class="content">
          <h1 class="has-text-centered">New Transaction</h1>

          <%= render 'form', user_transaction: @user_transaction %>

          
        </div>
      </div>
        <footer class="card-footer">
          <div class="column is-6 has-text-centered">
            <%= link_to 'Back', user_transactions_path, class:"button is-dark card-footer-items is-fullwidth" %>
          </div>
        </footer>
    </div>
  </div>
</div>

app/views/user_transactions/show.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-mobile">
    <p id="notice"><%= notice %></p>
    <div class="card">
      <div class="card-content">
        <div class="content">
          <div class="columns is-flex-mobile">
            <div class="column">
              <p>
                <strong>Name:</strong>
                <%= @user_transaction.name %>
              </p>
            </div>
            <div class="column">
              <p>
                <strong>Amount:</strong>
                $<%= @user_transaction.amount %>
              </p>
            </div>
          </div>

          <% @group_transactions.each do |group|%>
            <% unless transaction_already_in_group(group, @user_transaction) %>
              <div class="box">
                <div class="columns is-centered is-flex-mobile">
                  <div class="column is-4"><%=icon(group.icon) %> </div>
                  <div class="column is-4"><%= group.name %></div>
                  <div class="column is-4 has-text-right">
                    <%= form_for @group_transaction, method: :post do |f| %>
                      <%= f.text_field :group_id, value: group.id, type: :hidden %>
                      <%= f.text_field :user_transaction_id, value: @user_transaction.id, type: :hidden %>
                      <%= f.submit "add to group", class:"button is-success" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="columns mt-3 is-flex-mobile">
      <div class="column has-text-centered">
        <%= link_to 'Edit', edit_user_transaction_path(@user_transaction), class:"button is-success" %>
      </div>
      <div class="column has-text-centered">
        <%= link_to 'Back', user_transactions_path, class:"button is-dark" %>
      </div>
    </div>
  </div>
</div>