config/routes.rb
Rails.application.routes.draw do
  resources :home, only: %i[index]
  resources :external_transactions, only: %i[index]
  resources :group_transactions, only: %i[create new] do
    match '/new', to: 'group_transactions#create', via: :post, on: :collection
  end
  resources :user_transactions do
    put :update_payments, on: :member
    put :archieve_payments, on: :member
    get :archieved_transactions, on: :collection
  end
  resources :groups
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_transactions, dependent: :destroy
  has_many :user_transactions, through: :group_transactions, dependent: :destroy

  validates :name,
            presence: true,
            length: { minimum: 6, maximum: 25 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all.order(:name)
  end

  # GET /groups/1 or /groups/1.json
  def show
    # show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    # edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:"label" %>
    <%= form.text_field :name, class:"input" %>
  </div>

  <div class="field outer-feild">
    <span class="mleft"><strong><%= form.label :icon %>(Choose An Icon bellow)</strong></span>
    <div class="container-div">
      <div class="columns is-flex-mobile">
        <div class="column is-4">
          <%= form.radio_button :icon, 'fab fa-amazon fa-2x' %> <i class="fab fa-amazon fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fab fa-shopify fa-2x' %> <i class="fab fa-shopify fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-briefcase-medical fa-2x' %> <i class="fas fa-briefcase-medical fa-2x"></i><br>
        </div>
      </div>

      <div class="columns is-flex-mobile">
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-money-bill-alt fa-2x' %> <i class="fas fa-money-bill-alt fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fab fa-500px fa-2x' %> <i class="fab fa-500px fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fab fa-bitcoin fa-2x' %> <i class="fab fa-bitcoin fa-2x"></i><br>
        </div>
      </div>

      <div class="columns is-flex-mobile">
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-ad fa-2x' %> <i class="fas fa-ad fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fab fa-apple fa-2x' %> <i class="fab fa-apple fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-atlas fa-2x' %> <i class="fas fa-atlas fa-2x"></i><br>
        </div>
      </div>

      <div class="columns is-flex-mobile">
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-folder-open fa-2x' %> <i class="fas fa-folder-open fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-gas-pump fa-2x' %> <i class="fas fa-gas-pump  fa-2x"></i><br>
        </div>
        <div class="column is-4">
          <%= form.radio_button :icon, 'fas fa-plane-departure fa-2x' %> <i class="fas fa-plane-departure  fa-2x"></i><br>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-success is-fullwidth" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-mobile">
    <div class="card">
      <h1 class="has-text-centered"><strong>Editing Group</strong></h1>
      <div class="card-content">
        <div class="content">
          <%= render 'form', group: @group %>
        </div>
      </div>
      <footer class="card-footer">
        <div class="column is-6 has-text-centered">
          <%= link_to 'Show', @group, class:"card-footer-items button is-success is-fullwidth" %> 
        </div>
        <div class="column is-6 has-text-centered">
          <%= link_to 'Back', groups_path, class:"card-footer-items button is-dark is-fullwidth" %>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-tablet">
    <div class="card">
      <div class="card-content">
        <div class="content">
            <% @groups.each do |group| %>
              <div class="box">
                <%= link_to group do %>
                  <div class="columns is-flex-mobile">
                    <div class="column is-3 has-text-dark">
                      <%= icon(group.icon)%>
                    </div>
                    <div class="column is-5 has-text-dark has-text-centered">
                      <%= group.name %>
                    </div>
                    <div class="column is-4 has-text-dark has-text-centered">
                      <i><%= group.created_at.strftime("%d %b %y") %></i>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Create A New Group', new_group_path, class:"button is-success is-fullwidth" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-mobile">
    <div class="card">
      <h1 class="has-text-centered"><strong>New Group</strong></h1>
      <div class="card-content">
        <div class="content">
          <%= render 'form', group: @group %>

          <%= link_to 'Back', groups_path, class:"button is-dark mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="columns is-centered">
  <div class="column is-6-desktop is-12-mobile is-12-mobile">
    <div class="card">
      <div class="card-content">
        <div class="content">
          <p id="notice"><%= notice %></p>
          <div class="columns is-centered is-flex-mobile">
            <div class="column is-6 has-text-centered">
              <span>
                <%= icon(@group.icon) %>
                <span class="is-size-2">
                  <%= @group.name.capitalize %>
                </span>
              </span>
            </div>
          </div>

          <div class="columns is-centered is-flex-mobile">
            <div class="column is-6">
              <span>
                <strong><u>Group Transactions Total Amount:</u></strong>
              </span>
            </div>
            <div class="column is-3">
              <span>
                <u>$<%= group_transactions_total(@group) %></u>
              </span>
            </div>
          </div>

          <div class="ml-5 outer-feild">
            <h1 class='has-text-centered'>Group transactions</h1>
            <% @group.user_transactions.archieved.each do |transaction| %>
              <div class="box">
                <div class="columns is-flex-mobile">
                  <div class="column is-4">
                    <%= transaction.name %>
                  </div>
                  <div class="column is-3 has-text-centered">
                    <strong>$</strong> <%=transaction.amount %>
                  </div>

                  <div class="column is-5 has-text-right">
                    <i><strong>Created by:</strong> <%= transaction.user.username.capitalize %></i>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

        </div>
      </div>
      <footer class="card-footer is-flex-mobile">
        <div class="column is-6 has-text-centered">
          <%= link_to 'Edit', edit_group_path(@group), class:"card-footer-items button is-success is-fullwidth" %>
        </div>
        <div class="column is-6 has-text-centered">
          <%= link_to 'Back', groups_path, class:"card-footer-items button is-dark is-fullwidth" %>
        </div>
      </footer>
    </div>
  </div>
</div>