config/routes.rb
Rails.application.routes.draw do
  resources :home, only: %i[index]
  resources :external_transactions, only: %i[index]
  resources :group_transactions, only: %i[create new] do
    match '/new', to: 'group_transactions#create', via: :post, on: :collection
  end
  resources :user_transactions do
    put :update_payments, on: :member
    put :archieve_payments, on: :member
    get :archieved_transactions, on: :collection
  end
  resources :groups
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/group_transactions_controller.rb
class GroupTransactionsController < ApplicationController
  before_action :set_group_transaction, only: %i[show edit update destroy]

  # GET /group_transactions or /group_transactions.json
  def index
    @group_transactions = GroupTransaction.all
  end

  # GET /group_transactions/1 or /group_transactions/1.json
  def show
    # show
  end

  # GET /group_transactions/new
  def new
    @group_transaction = GroupTransaction.new
  end

  # GET /group_transactions/1/edit
  def edit
    # edit
  end

  # POST /group_transactions or /group_transactions.json
  def create
    @group_transaction = GroupTransaction.new(group_transaction_params)

    respond_to do |format|
      if @group_transaction.save
        format.html { redirect_to user_transactions_path, notice: 'Group transaction was successfully created.' }
        format.json { render :show, status: :created, location: @group_transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_transactions/1 or /group_transactions/1.json
  def update
    respond_to do |format|
      if @group_transaction.update(group_transaction_params)
        format.html { redirect_to @group_transaction, notice: 'Group transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_transactions/1 or /group_transactions/1.json
  def destroy
    @group_transaction.destroy
    respond_to do |format|
      format.html { redirect_to group_transactions_url, notice: 'Group transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_transaction
    @group_transaction = GroupTransaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_transaction_params
    params.require(:group_transaction).permit(:group_id, :user_transaction_id)
  end
end

app/helpers/group_transactions_helper.rb
module GroupTransactionsHelper
end

app/views/group_transactions/_form.html.erb
<%= form_with(model: group_transaction, local: true) do |form| %>
  <% if group_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_transaction.errors.count, "error") %> prohibited this group_transaction from being saved:</h2>

      <ul>
        <% group_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :user_transaction_id %>
    <%= form.text_field :user_transaction_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_transactions/edit.html.erb
<h1>Editing Group Transaction</h1>

<%= render 'form', group_transaction: @group_transaction %>

<%= link_to 'Show', @group_transaction %> |
<%= link_to 'Back', group_transactions_path %>

app/views/group_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>User transaction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_transactions.each do |group_transaction| %>
      <tr>
        <td><%= group_transaction.group_id %></td>
        <td><%= group_transaction.user_transaction_id %></td>
        <td><%= link_to 'Show', group_transaction %></td>
        <td><%= link_to 'Edit', edit_group_transaction_path(group_transaction) %></td>
        <td><%= link_to 'Destroy', group_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Transaction', new_group_transaction_path %>

app/views/group_transactions/new.html.erb
<h1>New Group Transaction</h1>

<%= render 'form', group_transaction: @group_transaction %>

<%= link_to 'Back', group_transactions_path %>

app/views/group_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @group_transaction.group_id %>
</p>

<p>
  <strong>User transaction:</strong>
  <%= @group_transaction.user_transaction_id %>
</p>

<%= link_to 'Edit', edit_group_transaction_path(@group_transaction) %> |
<%= link_to 'Back', group_transactions_path %>