config/routes.rb
Rails.application.routes.draw do
  resources :home, only: %i[index]
  resources :external_transactions, only: %i[index]
  resources :group_transactions, only: %i[create new] do
    match '/new', to: 'group_transactions#create', via: :post, on: :collection
  end
  resources :user_transactions do
    put :update_payments, on: :member
    put :archieve_payments, on: :member
    get :archieved_transactions, on: :collection
  end
  resources :groups
  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="columns is-centered has-background-primary">
  <div class="column is-6-desktop is-12-mobile">
    <div class="user-profile has-text-white has-text-centered">
      <div><%= profile_icon %></div>
      <div><%= current_user.username.capitalize %></div>
    </div>
    <div class="links-containers has-text-centered" id="myLinks">
      <%= link_to user_transactions_path, class:"has-text-white" do %>
        <span><i class="fas fa-money-bill-alt fa-2x"></i><span class="is-size-3"> All My Transactions</span></span>
      <% end %>
      <%= link_to external_transactions_path, class:"has-text-white"  do %>
        <span><i class="fas fa-money-bill-alt fa-2x"></i><span class="is-size-3"> All External Transactions</span></span>
      <% end %>
      <%= link_to  groups_path, class:"has-text-white"  do %>
        <span><i class="fas fa-users-cog fa-2x"></i><span class="is-size-3"> All Groups</span></span>
      <% end %>
      <%= link_to  destroy_user_session_path, method: :delete, class:"has-text-white last-elem my-5 py-5 has-text-centered"  do %>
        <span><i class="fas fa-sign-out-alt"></i><span class="is-size-4">Sign Out</span></span>
      <% end %>
    </div>
  </div>
</div>